#' @title Create EAD Domains
#' @description This function creates EAD domains and returns the design structure matrices (DSMs), the domain mapping matrices (DMMs) and the product matrices (P).
#' The following matrices are created
#' @param P_FD The product matrix representing the functional requirements (FRs)
#' @param N_DD The number of elements in the physcial domain (PD)
#' @param N_PrD The number of elements in the process domain (PrD)
#' @param N_RD The number of elements in the resource domain (RD)
#' @param DMM_PAR System design complexity for the DMMs. In the current version this values is applied for all domains.
#' @param DSM_method A method how to generate the DSM pattern. The following options are available:
#' \describe{
#'   \item{DNS}{The DSM is generated by treating the \code{DSM_param} input as a desired density.}
#'   \item{modular}{See \link[EAD]{crt_DSM} for details.}
#' }
#' @param DSM_param Either the adjusted and normalized structural complexity measure or bounds \code{c(UB,LB)} for the desired density of DSM. The input depends on the selected \code{DSM_method}.
#' In the current version this values is applied for all domains.
#' @param ut_DMM Boolean. If \code{ut_DMM=TRUE}, the upper triangle DMMs are created representing indirect inter domain dependencies.
#' @return Returns an EAD object containing
#' \describe{
#'   \item{P}{A list of product matrices starting with the product represent in the functional domain (FD), the physical domain (PD), the proccess domain (PrD) and the resource domain (RD)}
#'   \item{DSM}{A list containing the Design Structure Matrices (DSM) for each domain.}
#'   \item{DMM}{A list containing the Domain Mapping Matrices (DMM) for each domain.}
#'   \item{measures}{A named list containing measures on system and product level.}
#'   \item{message}{A string containing messages from the simulation routine.}
#' }
#' @examples
#' require(tidyr)
#' P_FD<-expand_grid(FR1=c(0,1),
#' FR2=c(0,1),
#' FR3=c(0,1),
#' FR4=c(0,1))
#'
#' ## creates a EAD by using the Density method
#' ## In each DSM 10% of the entries are none zero
#' EAD<-crt_DOMAINS(P_FD=P_FD,
#'             N_DD=15,
#'             N_PrD=30,
#'             N_RD=50,
#'             DMM_PAR=c(0,1),
#'             DMM_method="DENS",
#'             DSM_method="DNS",
#'             DSM_param=c(0,0.2),
#'             ut_DMM=F)
#'
#' EAD$P$RD # for RES_CONS_PAT
#' EAD$DSM$DD # for the DSM in the physical domain
#' EAD$measures for the measures
crt_DOMAINS<-function(P_FD,
                      N_DD,
                      N_PrD,
                      N_RD,
                      DMM_PAR,
                      DMM_method=c("SDC","DNS"),
                      DSM_method=c("DNS","modular"),
                      DSM_param,
                      ut_DMM=F,
                      uB_DMM=1,
                      ub_DSM=1,
                      allowZero=F){


  suppressMessages(require(EAD))
  max_tries<-20
  message<-"success"

  if(length(DSM_param)==1){
    DSM_param<-rep(DSM_param,2)
  }else if(length(DSM_param)>4){
    stop("DSM_param length is >4!")
  }

  tries<-0
  repeat{
    measures<-list()
    P<-list()
    P[['FD']]<-as.matrix(P_FD)
    N_FR<-NCOL(P_FD)
    ### 2.1 FD->PD (DMM_FD_PD) ###
    DMM_FD_PD<-crt_DMM(N_src = N_FR,
                       N_tgt = N_DD,
                       DMM_PAR = runif(1,min=DMM_PAR$FD_PD[[1]][1],max=DMM_PAR$FD_PD[[1]][2]),
                       method=DMM_method,
                       binary=F,
                       upper_Bound=uB_DMM,
                       allowZero = allowZero)
    ### 2.2 PD->PrD (DMM_PD_PrD) ###
    DMM_PD_PrD<-crt_DMM(N_src =N_DD,
                        N_tgt = N_PrD,
                        DMM_PAR = runif(1,min=DMM_PAR$PD_PrD[[1]][1],max=DMM_PAR$PD_PrD[[1]][2]),
                        method=DMM_method,
                        binary=F,
                        upper_Bound=uB_DMM,
                        allowZero = allowZero)
    ### 2.3 PD->PrD (DMM_PrD_RD) ###
    DMM_PrD_RD<-crt_DMM(N_src =N_PrD,
                        N_tgt = N_RD,
                        DMM_PAR = runif(1,min=DMM_PAR$PrD_RD[[1]][1],max=DMM_PAR$PrD_RD[[1]][2]),
                        method=DMM_method,
                        binary=F,
                        upper_Bound=uB_DMM,
                        allowZero = allowZero)

    ### 2.4  Create Off diagonal DMMs (DMM_FD_PrD,DMM_FD_RD) ###
    ## only if ut_DMM==T
    if(ut_DMM){
      DMM_FD_PrD<-crt_DMM(N_src =N_FR,
                          N_tgt = N_PrD,
                          DMM_PAR = runif(1,min=DMM_PAR$FD_PrD[[1]][1],max=DMM_PAR$FD_PrD[[1]][2]),
                          method=DMM_method,
                          binary=F,
                          upper_Bound=uB_DMM,
                          allowZero = allowZero)
      DMM_FD_RD<-crt_DMM(N_src =N_FR,
                         N_tgt = N_RD,
                         DMM_PAR = runif(1,min=DMM_PAR$FD_RD[[1]][1],max=DMM_PARFD_RD[[1]][2]),
                         method=DMM_method,
                         binary=F,
                         upper_Bound=uB_DMM,
                         allowZero = allowZero)
      DMM_PD_RD<-crt_DMM(N_src =N_DD,
                         N_tgt = N_RD,
                         DMM_PAR = runif(1,min=DMM_PAR$PD_RD[[1]][1],max=DMM_PAR$PD_RD[[1]][2]),
                         method=DMM_method,
                         binary=F,
                         upper_Bound=uB_DMM,
                         allowZero = allowZero)
    }else{
      DMM_FD_PrD<-list(DMM=matrix(0,
                                  nrow = N_FR,
                                  ncol = N_PrD),
                       SDC=NA)
      DMM_FD_RD<-list(DMM=matrix(0,
                                 nrow = N_FR,
                                 ncol = N_RD),
                      SDC=NA)
      DMM_PD_RD<-list(DMM=matrix(0,
                                 nrow = N_DD,
                                 ncol = N_RD),
                      SDC=NA)

    }

    ### 2.5 Write Measures for DMMs ###
    measures[['SYSTEM']]<-list(SDC=list(FD_PD = DMM_FD_PD$SDC,
                                     FD_PrD = DMM_FD_PrD$SDC,
                                     FD_RD = DMM_FD_RD$SDC,
                                     PD_PrD = DMM_PD_PrD$SDC,
                                     PD_RD = DMM_PD_RD$SDC,
                                     PrD_RD = DMM_PrD_RD$SDC),
                               SDC_n=list(FD_PD = DMM_FD_PD$SDC_n,
                                          FD_PrD = DMM_FD_PrD$SDC_n,
                                          FD_RD = DMM_FD_RD$SDC_n,
                                          PD_PrD = DMM_PD_PrD$SDC_n,
                                          PD_RD = DMM_PD_RD$SDC_n,
                                          PrD_RD = DMM_PrD_RD$SDC_n),
                            R=list(FD_PD = DMM_FD_PD$R,
                                   FD_PrD = DMM_FD_PrD$R,
                                   FD_RD = DMM_FD_RD$R,
                                   PD_PrD = DMM_PD_PrD$R,
                                   PD_RD = DMM_PD_RD$R,
                                   PrD_RD = DMM_PrD_RD$R),
                            S=list(FD_PD = DMM_FD_PD$S,
                                   FD_PrD = DMM_FD_PrD$S,
                                   FD_RD = DMM_FD_RD$S,
                                   PD_PrD = DMM_PD_PrD$S,
                                   PD_RD = DMM_PD_RD$S,
                                   PrD_RD = DMM_PrD_RD$S),
                            JSDC=list(FD_PD = DMM_FD_PD$JSDC,
                                      FD_PrD = DMM_FD_PrD$JSDC,
                                      FD_RD = DMM_FD_RD$JSDC,
                                      PD_PrD = DMM_PD_PrD$JSDC,
                                      PD_RD = DMM_PD_RD$JSDC,
                                      PrD_RD = DMM_PrD_RD$JSDC)
                            )

    DMM<-list(FD_PD = DMM_FD_PD$DMM,
              PD_PrD = DMM_PD_PrD$DMM,
              PrD_RD = DMM_PrD_RD$DMM,
              FD_PrD = DMM_FD_PrD$DMM,
              FD_RD = DMM_FD_RD$DMM,
              PD_RD = DMM_PD_RD$DMM)
    remove(DMM_FD_PrD)
    remove(DMM_FD_RD)
    remove(DMM_PD_RD)
    remove(DMM_FD_PD)
    remove(DMM_PD_PrD)
    remove(DMM_PrD_RD)

    ### 2.6 Create DSM matrices ###
    DSM_param_PD<-runif(1,min=DSM_param$PD[[1]][1],max=DSM_param$PD[[1]][2])
    DSM_param_PrD<-runif(1,min=DSM_param$PrD[[1]][1],max=DSM_param$PrD[[1]][2])
    DSM_param_RD<-runif(1,min=DSM_param$RD[[1]][1],max=DSM_param$RD[[1]][2])
    if(DSM_method=="DNS"){
      DSM_PD<-crt_DSM(N_el = N_DD,
                      method='DNS',
                      PARAM=list(DNS=DSM_param_PD),
                      upper_Bound = ub_DSM,
                      forced = which(colSums(DMM$FD_PD)==0))
      DSM_PrD<-crt_DSM(N_el = N_PrD,
                       method='DNS',
                       PARAM=list(DNS=DSM_param_PrD),
                       upper_Bound = ub_DSM,
                       forced = which(colSums(DMM$PD_PrD)==0))
      DSM_RD<-crt_DSM(N_el = N_RD,
                      method='DNS',
                      PARAM=list(DNS=DSM_param_RD),
                      upper_Bound = ub_DSM,
                      forced = which(colSums(DMM$PrD_RD)==0))
    }else if (DSM_method=="modular"){
      DSM_paramMOD_PD<-runif(1,min=DSM_param$PD[[1]][3],max=DSM_param$PD[[1]][4])
      DSM_paramMOD_PrD<-runif(1,min=DSM_param$PrD[[1]][3],max=DSM_param$PrD[[1]][4])
      DSM_paramMOD_RD<-runif(1,min=DSM_param$RD[[1]][3],max=DSM_param$RD[[1]][4])
      DSM_PD<-crt_DSM(N_el = N_DD,
                      method='modular',
                      PARAM=list(DNS=DSM_param_PD,
                                 modular = DSM_paramMOD_PD),
                      upper_Bound = ub_DSM,
                      forced = which(colSums(DMM$FD_PD)==0))
      DSM_PrD<-crt_DSM(N_el = N_PrD,
                       method='modular',
                       PARAM=list(DNS=DSM_param_PrD,
                                  modular = DSM_paramMOD_PrD),
                       upper_Bound = ub_DSM,
                       forced = which(colSums(DMM$PD_PrD)==0))
      DSM_RD<-crt_DSM(N_el = N_RD,
                      method='modular',
                      PARAM=list(DNS = DSM_param_RD,
                                 modular = DSM_paramMOD_RD),
                      upper_Bound = ub_DSM,
                      forced = which(colSums(DMM$PrD_RD)==0))
    }



    ### 2.7 Write Measures for DSMs ###
    measures[['SYSTEM']]<-c(measures[['SYSTEM']],
                              list(SC=list(PD = DSM_PD$measures$SC,
                                      PrD = DSM_PrD$measures$SC,
                                      RD = DSM_RD$measures$SC),
                                  Q=list(PD = DSM_PD$measures$Q,
                                         PrD = DSM_PrD$measures$Q,
                                         RD = DSM_RD$measures$Q),
                                  NE=list(PD = DSM_PD$measures$NE,
                                          PrD = DSM_PrD$measures$NE,
                                          RD = DSM_RD$measures$NE),
                                  DENS_DSM=list(PD = DSM_PD$measures$DENS_DSM,
                                                PrD = DSM_PrD$measures$DENS_DSM,
                                                RD = DSM_RD$measures$DENS_DSM),
                                  MCC=list(PD = DSM_PD$measures$MCC,
                                           PrD = DSM_PrD$measures$MCC,
                                           RD = DSM_RD$measures$MCC),
                                  MCC_n=list(PD = DSM_PD$measures$MCC_n,
                                           PrD = DSM_PrD$measures$MCC_n,
                                           RD = DSM_RD$measures$MCC_n),
                                  HVM=list(PD = DSM_PD$measures$HVM,
                                           PrD = DSM_PrD$measures$HVM,
                                           RD = DSM_RD$measures$HVM),
                                  HVM_n=list(PD = DSM_PD$measures$HVM_n,
                                           PrD = DSM_PrD$measures$HVM_n,
                                           RD = DSM_RD$measures$HVM_n),
                                  HIC=list(PD = DSM_PD$measures$HIC,
                                           PrD = DSM_PrD$measures$HIC,
                                           RD = DSM_RD$measures$HIC),
                                  HIC_n=list(PD = DSM_PD$measures$HIC_n,
                                           PrD = DSM_PrD$measures$HIC_n,
                                           RD = DSM_RD$measures$HIC_n)
                              )
                            )


    DSM<-list(PD = DSM_PD$DSM,
              PrD = DSM_PrD$DSM,
              RD = DSM_RD$DSM)

    remove(DSM_PD)
    remove(DSM_PrD)
    remove(DSM_RD)


    #### 2.8. calculate product matrices ####
    ### 2.8.1 Calculate Physical Domain ###
    P_DD_1 <- P$FD %*% DMM$FD_PD
    P_DD_2 <- P_DD_1 %*% DSM$PD
    ### second multiply with DSM
    P[["PD"]] <- pmax(P_DD_1,P_DD_2)
    remove(P_DD_1,P_DD_2)

    ### 2.8.2 Calculate Process Domain ###
    P[["PrD"]] <- P[["PD"]] %*% (( DMM$PD_PrD %*% DSM$PrD) + DMM$PD_PrD) + P[["FD"]] %*% DMM$FD_PrD

    ### 2.8.3 Calculate Resource Domain ###
    P[["RD"]] <- P[["PrD"]] %*% (( DMM$PrD_RD %*% DSM$RD) + DMM$PrD_RD) + P[["FD"]] %*% DMM$FD_RD + P[["PD"]] %*% DMM$PD_RD


    #### 2.9 Final Checks ####
      tries<-tries+1
      # cond_unique_RD<-NROW(unique(P[["RD"]]))==NROW(P[['FD']])
      # cond_unique_PrD<-NROW(unique(P[["PrD"]]))==NROW(P[['FD']])
        cond_unique_RD<-TRUE
        cond_unique_PrD<-TRUE
      cond_unique_PD<-NROW(unique(P[["PD"]]))==NROW(P[['FD']])

      cond_noneZERO_RD<-all(colSums(P[["RD"]])>0)
      cond_noneZERO_PrD<-all(colSums(P[["PrD"]])>0)
      cond_noneZERO_PD<-all(colSums(P[["PD"]])>0)

    if(all(cond_unique_RD, cond_unique_PrD, cond_unique_PD,
           cond_noneZERO_RD, cond_noneZERO_PrD, cond_noneZERO_PD)){
      message(paste0("Solution for domain design found after: ",tries, " iterations."))
      break
      }
    if(tries>max_tries){
      message<-"failed"
      break
    }
  }

  #### 2.10 Write Output object ####
  measures[['PRODUCT']]<-list(
                             INTER=list(FD=measure_INTER(P$FD),
                                        PD=measure_INTER(P$PD),
                                        PrD=measure_INTER(P$PrD),
                                        RD=measure_INTER(P$RD)),
                             INTRA=list(FD=measure_INTRA(P$FD,norm=T),
                                        PD=measure_INTRA(P$PD,norm=T),
                                        PrD=measure_INTRA(P$PrD,norm=T),
                                        RD=measure_INTRA(P$RD,norm=T)),
                             LOF=list(FD=measure_LOF(P$FD),
                                         PD=measure_LOF(P$PD),
                                         PrD=measure_LOF(P$PrD),
                                         RD=measure_LOF(P$RD)))

  measures[['SYSTEM']]<-c(measures[['SYSTEM']],
                         list(DNS=list(FD=measure_DENS(P$FD),
                                        PD=measure_DENS(P$PD),
                                         PrD=measure_DENS(P$PrD),
                                         RD=measure_DENS(P$RD)),
                              PCI=list(FD=measure_PCI(P$FD),
                                       PD=measure_PCI(P$PD),
                                       PrD=measure_PCI(P$PrD),
                                       RD=measure_PCI(P$RD)),
                              D_u=list(FD=measure_diversificationINDEX(P$FD),
                                       PD=measure_diversificationINDEX(P$PD),
                                       PrD=measure_diversificationINDEX(P$PrD),
                                       RD=measure_diversificationINDEX(P$RD)),
                              NPV=list(FD=measure_NPV(P$FD)),
                              CI=list(FD=measure_CI(P$FD),
                                      PD=measure_CI(P$PD),
                                      PrD=measure_CI(P$PrD),
                                      RD=measure_CI(P$RD)),
                              OV=list(FD=measure_OV(P$FD),
                                      PD=measure_OV(P$PD),
                                      PrD=measure_OV(P$PrD),
                                      RD=measure_OV(P$RD))
                              ))

  out<-list(P=P,
            DSM=DSM,
            DMM=DMM,
            measures=measures,
            message=message)
  return(out)

}
