#' @name genRC
#' @title Generates resource costs
#' @description The resource costs are generated by Anand et al. (2017) procedure.
#' @param n_RES Number of resources.
#' @param DISP1 The number of top resources which should allocate at DISP2 percent of total costs.
#' Therefore 1<=DISP1<NUMB_RES.
#' @param DISP2 How much percentage of total costs are assigned to the top DISP1 resources? DISP2 0<DISP2<1 \cr
#' @param TC A integer of total costs.
#' @examples
#' # Anand's standard setting
#' DISP1<-10
#' DISP2<-0.30
#' TC<-10^6
#'
#' RC<-genRC(n_RES=50,DISP1,DISP2,TC)
genRC<-function(n_RES,DISP1=10,DISP2,TC){


  #### Input for testing ####
  # NUMB_RES<-50
  # TC<-10^6
  # DISP2<-.34
  # DISP1<-10
  #### END Input for Testing ####

  NUMB_RES<-n_RES

  ## Flowchart 5.4(b)

  # Step 1
  r_MIN<-((1-DISP2)*TC)/(NUMB_RES-DISP1)

  #Step 2
  r1_MAX<-(DISP2*TC)-(DISP1-1)*r_MIN

  # Step 3
  r_MIN<-r_MIN+(r1_MAX-r_MIN)*0.025

  ## Step 4
  #Initalize Values
  RC<-vector(mode="numeric")
  r_MAX<-vector(mode="numeric")
  temp1_ADD<-vector(mode="numeric")
  temp1_ADD[1]<-0


  for (i in 1:(DISP1-1)) {

    r_MAX[i]<-(DISP2*TC-sum(temp1_ADD))-(DISP1-i)*r_MIN

    RC[i]<-runif(1,min=r_MIN,max=r_MAX[i])
    temp1_ADD[i]<-RC[i]


  }

  ## The final element is computed to ensure that the total rescource cost is exactly DISP2*TC
  RC<-c(RC,DISP2*TC-sum(temp1_ADD))

  ## Move the biggest resource to the front
  largest_RC<-sort(RC,decreasing = TRUE,index.return=TRUE)$ix[1]
  RC<-c(RC[largest_RC],RC[-largest_RC])


  #### Generate Small Rescources ####

  RC_small<-runif(length((length(RC)+1):NUMB_RES),min=0.05,max=0.95)
  RC_small<-RC_small/sum(RC_small) #normalize
  RC_small<-RC_small*(1-DISP2)*TC


  ## Some Checks ##
  # Sum of first DISP1 resources not correct.
  # if(min(RC)> ((1-DISP2)*TC)/(NUMB_RES-DISP1)){

  while(max(RC_small) - min(RC) > 1.0) {

    RC_small<-sort(RC_small,decreasing = TRUE)
    min_bigRes<-min(RC)
    for (i in 1:(length(RC_small))) {
      overage <- max(c(RC_small[i] -min_bigRes ,0))
      RC_small[i]<-RC_small[i]-overage
      RC_small[length(RC_small) - i+1]<-RC_small[length(RC_small) - i+1]+overage
    }
  }


  # Step 6 Schuffle small rescources
  RC_small<-RC_small[sample(length(RC_small))]
  RC<-c(RC,RC_small)

  # sum(RC)
  RCs<-sort(RC,decreasing = TRUE,index.return=TRUE)
  RC<-list(RC=RC,CHECK=list(cost_largestRCP=RCs$x[1]/RCs$x[NUMB_RES],cost_topTEN=sum(RCs$x[1:10])/TC,DISP1=DISP1,DISP2=DISP2))

  # RC$CHECK



  return(RC)
}

